### ISSUE TITLE
Missing titleDeterminer?

### ISSUE THREAD

**Issue by LiveNathan** [habuma/spring-ai-examples#5]
https://github.com/habuma/spring-ai-examples/blob/3048bbd0190963b0c991eda86c086bd2bc876b84/vector-store-loader/src/main/java/com/example/vectorstoreloader/VectorStoreLoaderApplication.java#L70

Looks like we are missing the titleDeterminer from chapter 3?

**Comment by habuma** [comment]
This isn't intended to be a complete recreation of the example from my book. It's a slightly simpler example. The book's source code will be available separately (as a downloadable zip and via a separate Git repository).
